# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-10 04:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sindicato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('endereco', models.CharField(max_length=100)),
                ('numero', models.CharField(max_length=5)),
                ('bairro', models.CharField(max_length=100)),
                ('cep', models.CharField(max_length=10)),
                ('cnpj', models.CharField(max_length=100)),
                ('presidente', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Socio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=15)),
                ('rg', models.CharField(max_length=7)),
                ('ssp', models.CharField(max_length=3, verbose_name='SSP')),
                ('data_exp', models.DateField(verbose_name='Data de Expedissão')),
                ('cnh', models.CharField(max_length=12, verbose_name='CNH')),
                ('categoria', models.CharField(max_length=5)),
                ('titulo', models.CharField(max_length=15)),
                ('nacionalidade', models.CharField(max_length=100)),
                ('fator_rh', models.CharField(max_length=50, verbose_name='Fator RH')),
                ('naturalidade', models.CharField(max_length=100)),
                ('uf', models.CharField(max_length=3)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=128)),
                ('matricula', models.CharField(max_length=50)),
                ('data_admissao', models.DateField(verbose_name='Data de Ademissão')),
                ('data_nascimento', models.DateField(verbose_name='Data de Nascimento')),
                ('estado_sivil', models.CharField(choices=[('C', 'Casado(a)'), ('S', 'Solteiro(a)'), ('D', 'Divorciado(a)'), ('V', 'Viuvo(a)'), ('O', 'Outros')], max_length=1)),
                ('conjugue', models.CharField(max_length=100, verbose_name='Cônjuge')),
                ('dependentes', models.IntegerField()),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email de Contato')),
                ('profissao', models.CharField(max_length=100, verbose_name='Profissão')),
                ('pai', models.CharField(max_length=100)),
                ('mae', models.CharField(max_length=100, verbose_name='Mãe')),
                ('endereco', models.CharField(max_length=150, verbose_name='Endereço')),
                ('numero', models.CharField(max_length=10, verbose_name='Nº')),
                ('bairro', models.CharField(max_length=150)),
                ('cep', models.CharField(max_length=9)),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=3)),
                ('fone_resid', models.CharField(max_length=7, verbose_name='Fone Residencial')),
                ('celular', models.CharField(max_length=7)),
                ('placa_veiculo', models.CharField(max_length=7, verbose_name='Placa do Veiculo')),
                ('concessao', models.CharField(max_length=7, verbose_name='Concessão')),
                ('categorias', models.CharField(max_length=1, verbose_name=(('P', 'Prop.'), ('A', 'Alx.')))),
                ('foto', models.FileField(upload_to='photos')),
                ('sindicato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_sindicato.Sindicato')),
            ],
            options={
                'verbose_name': 'Sócio',
            },
        ),
    ]
