# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-12 03:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_sindicato', '0002_auto_20170510_0105'),
    ]

    operations = [
        migrations.AddField(
            model_name='socio',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='socio',
            name='cep',
            field=models.CharField(max_length=9, verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='socio',
            name='cpf',
            field=models.CharField(max_length=15, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='socio',
            name='email',
            field=models.EmailField(default=1, max_length=254, verbose_name='Email de Contato'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='socio',
            name='foto',
            field=models.FileField(blank=True, upload_to='static/photos/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='socio',
            name='rg',
            field=models.CharField(max_length=7, verbose_name='RG'),
        ),
        migrations.AlterField(
            model_name='socio',
            name='uf',
            field=models.CharField(max_length=3, verbose_name='UF'),
        ),
    ]
