# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-13 13:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_sindicato', '0003_auto_20170511_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socio',
            name='added_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Cadastrado Por'),
        ),
        migrations.AlterField(
            model_name='socio',
            name='celular',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='socio',
            name='conjugue',
            field=models.CharField(blank=True, max_length=100, verbose_name='Cônjuge'),
        ),
        migrations.AlterField(
            model_name='socio',
            name='dependentes',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='socio',
            name='fone_resid',
            field=models.CharField(max_length=10, verbose_name='Fone Residencial'),
        ),
        migrations.AlterField(
            model_name='socio',
            name='foto',
            field=models.FileField(blank=True, upload_to='static/img/%d'),
        ),
        migrations.AlterField(
            model_name='socio',
            name='placa_veiculo',
            field=models.CharField(max_length=10, verbose_name='Placa do Veiculo'),
        ),
    ]
